theme: jekyll-theme-architect

title: [glassfish-samples]
description: [GlassFish Samples Project]

# sidebar links url
links:
  source: https://github.com/javaee/glassfish-samples
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

